import {
  Apple,
  Ear,
  Watch,
  Tag,
  Tablet,
  Laptop,
  Gamepad2,
  Xbox,
  Bot,
  Recycle,
  Camera,
  CameraIcon,
  Clock,
  Headphones,
  ShoppingBag,
  Headset,
  Sparkles,
  BadgeHelp,
  Palette,
  // Puedes sumar más Lucide icons si querés otras categorías
} from "lucide-react";

export const ICONOS_CATEGORIAS: Record<string, React.ComponentType<any>> = {
  IPHONE: Apple,
  AIRPODS: Ear,
  "APPLE WATCH": Watch,
  AIRTAG: Tag,
  IPAD: Tablet,
  "MACBOOK AIR": Laptop,
  "MACBOOK PRO": Laptop,
  PLAYSTATION: Gamepad2,
  XBOX: Xbox,
  "NINTENDO SWITCH": Gamepad2,
  VR: Headset,
  GOPRO: Camera,
  INSTA360: CameraIcon,
  SMARTWATCH: Clock,
  ACCESORIOS: ShoppingBag,
  "DRONE DJI": Bot,
  "IPHONE SEMINUEVOS": Recycle,
  // fallback
  DEFAULT: BadgeHelp,
};
