// lib/glosario.ts
export const GLOSARIO: Record<string, { adj: string; art: string }> = {
  AIRPODS: { adj: 'están disponibles', art: 'los' },
  AIRTAG: { adj: 'están disponibles', art: 'los' },
  'APPLE WATCH': { adj: 'está disponible', art: 'el' },
  'DRONE DJI': { adj: 'está disponible', art: 'el' },
  GOPRO: { adj: 'está disponible', art: 'la' },
  INSTA360: { adj: 'está disponible', art: 'la' },
  IPAD: { adj: 'está disponible', art: 'el' },
  IPHONE: { adj: 'está disponible', art: 'el' },
  MACBOOK: { adj: 'está disponible', art: 'la' },
  'NINTENDO SWITCH': { adj: 'está disponible', art: 'la' },
  PLAYSTATION: { adj: 'está disponible', art: 'la' },
  'SAMSUNG GALAXY': { adj: 'está disponible', art: 'el' },
  SMARTWATCH: { adj: 'están disponibles', art: 'los' },
  VR: { adj: 'están disponibles', art: 'los' },
  XBOX: { adj: 'está disponible', art: 'la' },
  XIAOMI: { adj: 'está disponible', art: 'el' },
  REALME: { adj: 'está disponible', art: 'el' },
  PIXEL: { adj: 'está disponible', art: 'el' },
}
